name: Lint & Test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # ruby 3.x
          - ruby: '3.2'
            gemfile: gemfiles/rails_81.gemfile
          - ruby: '3.2'
            gemfile: gemfiles/rails_80.gemfile
          - ruby: '3.2'
            gemfile: gemfiles/rails_72.gemfile
          - ruby: '3.2'
            gemfile: gemfiles/rails_71.gemfile
          # ruby 2.x
          - ruby: '2.7'
            gemfile: gemfiles/rails_72.gemfile
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake spec
